### PR TITLE
Remove  unused import

### PR DESCRIPTION
**Pull request by lookfwd**
Just kidding - but this improves runtime 2.5x (from 250ms to 90ms)

### CODE REVIEW

**Comment by lookfwd** [comment]
Just kidding - but this improves runtime 2.5x (from 250ms to 90ms)

**Comment by chris-ramon** [comment]
PR #124 should fix the build.

/cc: @slimsag

**Comment by slimsag** [comment]
haha @lookfwd I'm not sure how to take this PR :) obviously it's reactor is needed and it's a joke, but... what's the joke? :scream:

**Comment by lookfwd** [comment]
Are you sure it's needed in this file?

**Comment by slimsag** [comment]
Oh, doh, I was looking at `example_twisted.py` and saw `reactor` was used from there. You're 100% correct, for `example_socket.py` Twisted is obviously not needed. My bad! :smile: 

This change LGTM, thanks a ton for the contribution and sharp eyes!

**Comment by lookfwd** [comment]
I thank you for the patience. My typical response on such PR would be... man - go find me a real bug! :D Hahaha! Hopefully will be back with something more meaningful soon. Cheers!

**Pull request merged**
